"""CSV reader using DuckDB streaming for encoding support."""

from __future__ import annotations

import csv
import io
import re
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import TYPE_CHECKING, Any

import duckdb as _duckdb
import ibis
import polars as pl
import pyarrow as pa

from ..compression import (
    bounded_gzip_stream,
    decompressed_cap,
    is_gzipped,
    strip_compression_suffix,
)
from ..utils import log_error, log_warn
from ..preview import preview_from_arrow, preview_from_ibis
from .excel import is_valid_tabular_dataset
from .filesystem import ensure_local_utf8
from .utils import build_variables, deduplicate_columns

if TYPE_CHECKING:
    from collections.abc import Generator

    import pandas as pd

    from ..schema import Variable


_AUTOGENERATED_RE = re.compile(r"^column\d+$")


def _is_autogenerated(name: str) -> bool:
    """Check if a column name is auto-generated by DuckDB (e.g. 'column0')."""
    return _AUTOGENERATED_RE.match(name) is not None


_CSV_HEADER_DELIMITERS = ",;\t|"
# 64 KB covers ~1000 columns with long names (e.g. survey/clinical exports).
_CSV_HEADER_SAMPLE_BYTES = 64 * 1024

# Strings DuckDB should treat as NULL before type inference. Covers R
# ("NA"), pandas ("NaN"), Excel ("#N/A") and SQL ("NULL") conventions so a
# stray missing value far in the file does not invalidate a numeric column
# typed from the first 20 000-row sample.
_CSV_NULL_STRINGS = ["", "NA", "N/A", "n/a", "#N/A", "NULL", "null", "NaN", "nan"]
_CSV_NULL_STRINGS_KEEP_EMPTY = [s for s in _CSV_NULL_STRINGS if s != ""]

# Read profiles tried in order when DuckDB cannot parse or type a file — each
# rung degrades one dimension, cheapest fidelity loss first:
#   1. plain read;
#   2. lenient sniffing (strict mode occasionally rejects RFC 4180-compliant files);
#   3. ignore unconvertible rows in value passes — types and stats survive;
#   4. read everything as text — typed stats don't survive, every parseable
#      row does (ignore_errors only sheds lines that cannot be split at all).
# Rungs 3-4 are accepted only when the damage stays marginal (see
# _dropped_rows_tolerance). Values in a column are never altered: rows are
# ignored or kept verbatim, so a degraded dataset is incomplete or untyped,
# never wrong.
_CSV_READ_PROFILES: tuple[dict[str, Any], ...] = (
    {},
    {"strict_mode": False},
    {"strict_mode": False, "ignore_errors": True, "store_rejects": True},
    {
        "strict_mode": False,
        "all_varchar": True,
        "ignore_errors": True,
        "store_rejects": True,
    },
)


def _decode_csv_sample(sample: bytes, csv_encoding: str | None) -> str:
    """Decode a CSV byte sample to text: UTF-8 with cp1252 fallback, BOM stripped, LF-normalized."""
    try:
        text = sample.decode("utf-8")
    except UnicodeDecodeError:
        text = sample.decode(csv_encoding or "cp1252", errors="replace")
    # Strip UTF-8 BOM if present (common on Windows-exported CSVs)
    if text.startswith("\ufeff"):
        text = text[1:]
    # Normalize line endings: stdlib csv only accepts \n or \r\n, but some files
    # (Mac Classic, legacy SDMX exports) use bare \r as line terminator.
    return text.replace("\r\n", "\n").replace("\r", "\n").lstrip("\n")


def _csv_reader_from_text(text: str) -> Any:
    """Build a csv.reader with sniffed dialect, or None if text is blank."""
    if not text.strip():
        return None
    # Sniff dialect on a reasonable sample, restricted to common delimiters so
    # commas inside quoted header fields don't fool the sniffer when the real
    # separator is ';' (FR/DE/IT locales).
    try:
        dialect = csv.Sniffer().sniff(text, delimiters=_CSV_HEADER_DELIMITERS)
    except csv.Error:
        dialect = None  # type: ignore[assignment]
    return (
        csv.reader(io.StringIO(text), dialect)
        if dialect
        else csv.reader(io.StringIO(text))
    )


def _read_csv_header(sample: bytes, csv_encoding: str | None = None) -> list[str]:
    """Parse column names from a CSV header sample (raw bytes, may span multiple lines)."""
    reader = _csv_reader_from_text(_decode_csv_sample(sample, csv_encoding))
    if reader is None:
        return []
    row = next(reader, [])
    return deduplicate_columns([c for c in row if c.strip()])


@contextmanager
def _csv_source(
    file_path: Path,
    csv_encoding: str | None,
    csv_skip_copy: bool,
) -> Generator[Path, None, None]:
    """Provide a local UTF-8 CSV file for DuckDB to read."""
    gzipped = is_gzipped(file_path.name)
    # DuckDB can read a .gz directly, but that shortcut bypasses both the encoding
    # transcode (a gzipped cp1252 CSV would break) and the decompression-bomb guard,
    # so a gzipped source always goes through the transcode route below.
    if csv_skip_copy and not gzipped:
        try:
            con = ibis.duckdb.connect()
            try:
                con.read_csv(str(file_path)).limit(0).to_pyarrow()
            finally:
                con.disconnect()
            yield file_path
            return
        except Exception:
            pass  # fallback to ensure_local_utf8

    tmp_dir = Path(tempfile.mkdtemp())
    tmp_path = tmp_dir / strip_compression_suffix(file_path.name)
    try:
        with open(file_path, "rb") as raw:
            fin = (
                bounded_gzip_stream(raw, decompressed_cap(file_path.stat().st_size))
                if gzipped
                else raw
            )
            with open(tmp_path, "wb") as fout:
                ensure_local_utf8(fin, fout, csv_encoding)
        yield tmp_path
    finally:
        tmp_path.unlink(missing_ok=True)
        tmp_dir.rmdir()


def _read_preview_rows_csv(path: Path, *, n: int = 10) -> list[tuple[object, ...]]:
    """Read first n rows of a UTF-8 CSV file (auto-detects delimiter)."""
    with open(path, "rb") as fb:
        sample = fb.read(_CSV_HEADER_SAMPLE_BYTES)
    reader = _csv_reader_from_text(_decode_csv_sample(sample, None))
    if reader is None:
        return []
    rows: list[tuple[object, ...]] = []
    for row in reader:
        # Treat trailing empty fields as missing cells (None) for width checks
        cells = tuple(c if c != "" else None for c in row)
        rows.append(cells)
        if len(rows) >= n:
            break
    return rows


def _short_csv_error(exc: BaseException) -> str:
    """Return a one-line summary of a DuckDB CSV parse error."""
    msg = str(exc).split("\n", 1)[0]
    return msg.removeprefix("Invalid Input Error: ").strip()


def _dropped_rows_tolerance(row_count: int) -> int:
    """How many rows an ``ignore_errors`` rung may drop before it is refused:
    enough for stray footnotes (10), scaling to 0.1% on large files — a
    structurally broken file (bad quoting can invalidate half the lines) must
    never be silently mutilated — and always fewer than the rows kept, so a
    file whose every line drops stays unscannable rather than becoming a
    plausible-looking empty dataset."""
    return min(max(10, row_count // 1000), max(row_count - 1, 0))


def _count_rejected_lines(con: Any) -> int:
    """Distinct CSV lines dropped by an ``ignore_errors`` read, from the rejects
    table that ``store_rejects`` populates on this connection."""
    cursor: Any = con.raw_sql("SELECT count(DISTINCT line) FROM reject_errors")
    return int(cursor.fetchone()[0])


def read_csv(
    path: str | Path,
    *,
    csv_encoding: str | None = None,
    preserve_empty_strings: bool = False,
) -> pd.DataFrame | None:
    """Read a CSV file into a pandas DataFrame."""
    file_path = Path(path)

    if file_path.stat().st_size == 0:
        return None

    try:
        with _csv_source(file_path, csv_encoding, csv_skip_copy=False) as csv_path:
            con = ibis.duckdb.connect()
            try:
                null_strings = (
                    _CSV_NULL_STRINGS_KEEP_EMPTY
                    if preserve_empty_strings
                    else _CSV_NULL_STRINGS
                )
                table = con.read_csv(str(csv_path), nullstr=null_strings)
                result = table.to_pyarrow()
            finally:
                con.disconnect()
            # Drop empty or auto-generated trailing column names
            keep = [
                f.name
                for f in result.schema
                if f.name.strip() and not _is_autogenerated(f.name)
            ]
            if len(keep) < len(result.schema):
                result = result.select(keep)
            return result.to_pandas()
    except Exception:
        return None


def scan_csv(
    path: str | Path,
    *,
    dataset_id: str,
    infer_stats: bool = True,
    freq_threshold: int | None = None,
    csv_encoding: str | None = None,
    sample_size: int | None = None,
    preview_rows: int = 0,
    return_preview: bool = False,
    csv_skip_copy: bool = False,
    quiet: bool = False,
    path_label: str | None = None,
) -> tuple[Any, ...]:
    """Scan a CSV file and return (variables, row_count, actual_sample_size, freq_table)."""
    file_path = Path(path)
    label = path_label or file_path.name

    def result(
        variables: list[Variable],
        nb_row: int | None,
        actual_sample_size: int | None,
        freq_table: pa.Table | None,
        preview_df: pl.DataFrame | None,
    ) -> tuple[Any, ...]:
        if return_preview:
            return variables, nb_row, actual_sample_size, freq_table, preview_df
        return variables, nb_row, actual_sample_size, freq_table

    if file_path.stat().st_size == 0:
        return result([], 0, None, None, None)

    try:
        with _csv_source(file_path, csv_encoding, csv_skip_copy) as csv_path:
            # Pre-flight: structural check on first rows so non-tabular CSVs
            # (footers like "Ende/Fin/Fino", multi-line headers, irregular
            # widths from exported pivots) are flagged cleanly instead of
            # surfacing a DuckDB strict-mode traceback.
            try:
                preview = _read_preview_rows_csv(csv_path)
            except Exception:
                preview = []
            if preview:
                valid, reason = is_valid_tabular_dataset(preview)
                if not valid:
                    log_warn(
                        f"{label}: not a valid tabular dataset "
                        f"({reason}); skipped as untreatable",
                        quiet,
                    )
                    return result([], None, None, None, None)

            # Profile ladder: evaluation is lazy, so a parse or type-conversion
            # error can surface at any pass (count, sampling, stats, preview) —
            # each rung therefore wraps the whole scan body and a fresh
            # connection keeps the rejects count of one attempt isolated.
            last_error: Exception | None = None
            known_row_count: int | None = None
            needs_conversion_tolerance = False
            for profile in _CSV_READ_PROFILES:
                if needs_conversion_tolerance and not profile.get("ignore_errors"):
                    # A conversion error is about values, not sniffing — the
                    # dialect already fit every line (the count succeeded) —
                    # so lenient sniffing alone would fail identically.
                    continue
                con = ibis.duckdb.connect()
                try:
                    table = con.read_csv(
                        str(csv_path), nullstr=_CSV_NULL_STRINGS, **profile
                    )
                    # count(*) converts no column, so one successful count is
                    # valid for every rung — no full re-parse per attempt.
                    if known_row_count is None:
                        known_row_count = int(table.count().to_pyarrow().as_py())
                    scanned = _scan_csv_table(
                        con,
                        table,
                        known_row_count,
                        dataset_id=dataset_id,
                        infer_stats=infer_stats,
                        freq_threshold=freq_threshold,
                        sample_size=sample_size,
                        preview_rows=preview_rows,
                        label=label,
                        quiet=quiet,
                    )
                except (
                    _duckdb.InvalidInputException,
                    _duckdb.ConversionException,
                ) as exc:
                    last_error = exc
                    if isinstance(exc, _duckdb.ConversionException):
                        needs_conversion_tolerance = True
                    continue
                else:
                    nb_row = scanned[1]
                    dropped = (
                        _count_rejected_lines(con)
                        if profile.get("ignore_errors")
                        else 0
                    )
                    if dropped > _dropped_rows_tolerance(nb_row):
                        continue  # too mutilated — try text-only, else give up
                    if profile.get("all_varchar"):
                        unparseable = (
                            f"; {dropped} unparseable row(s) dropped" if dropped else ""
                        )
                        log_warn(
                            f"{label}: type conversion failed; all columns "
                            f"read as text (all_varchar fallback){unparseable}",
                            quiet,
                        )
                    elif dropped:
                        log_warn(
                            f"{label}: {dropped} unconvertible row(s) ignored "
                            f"by statistics (ignore_errors fallback); they "
                            f"still count in nb_row and appear as missing "
                            f"values",
                            quiet,
                        )
                    return result(*scanned)
                finally:
                    con.disconnect()

            assert last_error is not None  # the ladder only ends via exceptions
            if isinstance(last_error, _duckdb.InvalidInputException):
                log_warn(
                    f"{label}: unscannable CSV "
                    f"({_short_csv_error(last_error)}); skipped as untreatable",
                    quiet,
                )
                return result([], None, None, None, None)
            # A ConversionException that survives even all_varchar (which casts
            # nothing) is not a CSV problem — surface it as a real scan error.
            log_error(label, last_error, quiet)
            return result([], None, None, None, None)
    except Exception as e:
        log_error(label, e, quiet)
        return result([], None, None, None, None)


def _scan_csv_table(
    con: Any,
    table: ibis.Table,
    row_count: int,
    *,
    dataset_id: str,
    infer_stats: bool,
    freq_threshold: int | None,
    sample_size: int | None,
    preview_rows: int,
    label: str,
    quiet: bool,
) -> tuple[list[Variable], int, int | None, pa.Table | None, pl.DataFrame | None]:
    """One full scan attempt over an already-registered CSV view, returning
    ``(variables, nb_row, sample_size, freq_table, preview)``. DuckDB's parse and
    conversion errors propagate for the caller's profile ladder to catch."""
    if sample_size is not None and row_count > sample_size and infer_stats:
        # Sampling through the registered view applies the rung's read profile
        # by construction (same pattern as the parquet/statistical scanners).
        cursor: Any = con.raw_sql(
            f"SELECT * FROM {table.get_name()} "
            f"USING SAMPLE reservoir({sample_size} ROWS)"
        )
        sample_arrow = cursor.fetch_arrow_table()
        actual_sample_size = len(sample_arrow)
        preview_df = preview_from_arrow(
            sample_arrow, preview_rows, label=label, quiet=quiet
        )
        variables, freq_table = build_variables(
            ibis.memtable(sample_arrow),
            nb_rows=actual_sample_size,
            dataset_id=dataset_id,
            infer_stats=True,
            freq_threshold=freq_threshold,
            full_table=table,
            full_nb_rows=row_count,
        )
        return variables, row_count, actual_sample_size, freq_table, preview_df

    variables, freq_table = build_variables(
        table,
        nb_rows=row_count,
        dataset_id=dataset_id,
        infer_stats=infer_stats and row_count > 0,
        freq_threshold=freq_threshold,
    )
    preview_df = preview_from_ibis(table, preview_rows, label=label, quiet=quiet)
    return variables, row_count, None, freq_table, preview_df
