"""CSV reader using DuckDB streaming for encoding support."""

from __future__ import annotations

import csv
import io
import re
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import TYPE_CHECKING, Any

import ibis
import pyarrow as pa

from ..utils import log_error
from .filesystem import ensure_local_utf8
from .utils import build_variables

if TYPE_CHECKING:
    from collections.abc import Generator

    import pandas as pd

    from ..schema import Variable


_AUTOGENERATED_RE = re.compile(r"^column\d+$")


def _is_autogenerated(name: str) -> bool:
    """Check if a column name is auto-generated by DuckDB (e.g. 'column0')."""
    return _AUTOGENERATED_RE.match(name) is not None


_CSV_HEADER_DELIMITERS = ",;\t|"
# 64 KB covers ~1000 columns with long names (e.g. survey/clinical exports).
_CSV_HEADER_SAMPLE_BYTES = 64 * 1024


def _deduplicate_columns(names: list[str]) -> list[str]:
    """Suffix duplicate column names as DuckDB does (`name`, `name_1`, `name_2`, …)."""
    seen: dict[str, int] = {}
    out: list[str] = []
    for n in names:
        if n in seen:
            seen[n] += 1
            out.append(f"{n}_{seen[n]}")
        else:
            seen[n] = 0
            out.append(n)
    return out


def _read_csv_header(sample: bytes, csv_encoding: str | None = None) -> list[str]:
    """Parse column names from a CSV header sample (raw bytes, may span multiple lines)."""
    try:
        text = sample.decode("utf-8")
    except UnicodeDecodeError:
        text = sample.decode(csv_encoding or "cp1252", errors="replace")
    # Strip UTF-8 BOM if present (common on Windows-exported CSVs)
    if text.startswith("\ufeff"):
        text = text[1:]
    # Normalize line endings: stdlib csv only accepts \n or \r\n, but some files
    # (Mac Classic, legacy SDMX exports) use bare \r as line terminator.
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.lstrip("\n")
    if not text.strip():
        return []
    # Sniff dialect on a reasonable sample, restricted to common delimiters so
    # commas inside quoted header fields don't fool the sniffer when the real
    # separator is ';' (FR/DE/IT locales).
    try:
        dialect = csv.Sniffer().sniff(text, delimiters=_CSV_HEADER_DELIMITERS)
    except csv.Error:
        dialect = None  # type: ignore[assignment]
    reader = (
        csv.reader(io.StringIO(text), dialect)
        if dialect
        else csv.reader(io.StringIO(text))
    )
    row = next(reader, [])
    return _deduplicate_columns([c for c in row if c.strip()])


@contextmanager
def _csv_source(
    file_path: Path,
    csv_encoding: str | None,
    csv_skip_copy: bool,
) -> Generator[Path, None, None]:
    """Provide a local UTF-8 CSV file for DuckDB to read."""
    if csv_skip_copy:
        try:
            con = ibis.duckdb.connect()
            try:
                con.read_csv(str(file_path)).limit(0).to_pyarrow()
            finally:
                con.disconnect()
            yield file_path
            return
        except Exception:
            pass  # fallback to ensure_local_utf8

    tmp_dir = Path(tempfile.mkdtemp())
    tmp_path = tmp_dir / file_path.name
    try:
        with open(file_path, "rb") as fin, open(tmp_path, "wb") as fout:
            ensure_local_utf8(fin, fout, csv_encoding)
        yield tmp_path
    finally:
        tmp_path.unlink(missing_ok=True)
        tmp_dir.rmdir()


def read_csv(
    path: str | Path,
    *,
    csv_encoding: str | None = None,
) -> pd.DataFrame | None:
    """Read a CSV file into a pandas DataFrame."""
    file_path = Path(path)

    if file_path.stat().st_size == 0:
        return None

    try:
        with _csv_source(file_path, csv_encoding, csv_skip_copy=False) as csv_path:
            con = ibis.duckdb.connect()
            try:
                table = con.read_csv(str(csv_path))
                result = table.to_pyarrow()
            finally:
                con.disconnect()
            # Drop empty or auto-generated trailing column names
            keep = [
                f.name
                for f in result.schema
                if f.name.strip() and not _is_autogenerated(f.name)
            ]
            if len(keep) < len(result.schema):
                result = result.select(keep)
            return result.to_pandas()
    except Exception:
        return None


def scan_csv(
    path: str | Path,
    *,
    dataset_id: str,
    infer_stats: bool = True,
    freq_threshold: int | None = None,
    csv_encoding: str | None = None,
    sample_size: int | None = None,
    csv_skip_copy: bool = False,
    quiet: bool = False,
) -> tuple[list[Variable], int, int | None, pa.Table | None]:
    """Scan a CSV file and return (variables, row_count, actual_sample_size, freq_table)."""
    file_path = Path(path)

    if file_path.stat().st_size == 0:
        return [], 0, None, None

    try:
        with _csv_source(file_path, csv_encoding, csv_skip_copy) as csv_path:
            con = ibis.duckdb.connect()
            try:
                table = con.read_csv(str(csv_path))
                row_count = int(table.count().to_pyarrow().as_py())

                if row_count == 0:
                    variables, freq_table = build_variables(
                        table,
                        nb_rows=0,
                        dataset_id=dataset_id,
                        infer_stats=False,
                    )
                    return variables, 0, None, freq_table

                actual_sample_size: int | None = None
                if sample_size is not None and row_count > sample_size and infer_stats:
                    safe_path = str(csv_path).replace("'", "''")
                    cursor: Any = con.raw_sql(
                        f"SELECT * FROM read_csv('{safe_path}') "
                        f"USING SAMPLE reservoir({sample_size} ROWS)"
                    )
                    sample_arrow = cursor.fetch_arrow_table()
                    actual_sample_size = len(sample_arrow)
                    sample_table = ibis.memtable(sample_arrow)

                    variables, freq_table = build_variables(
                        sample_table,
                        nb_rows=actual_sample_size,
                        dataset_id=dataset_id,
                        infer_stats=True,
                        freq_threshold=freq_threshold,
                        full_table=table,
                        full_nb_rows=row_count,
                    )
                else:
                    variables, freq_table = build_variables(
                        table,
                        nb_rows=row_count,
                        dataset_id=dataset_id,
                        infer_stats=infer_stats,
                        freq_threshold=freq_threshold,
                    )
            finally:
                con.disconnect()
    except Exception as e:
        log_error(file_path.name, e, quiet)
        return [], 0, None, None

    return variables, row_count, actual_sample_size, freq_table
