name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: CI (lint)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv sync --frozen
      - run: make lint
      - run: make typecheck

  test:
    name: CI (${{ matrix.python-version }})
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-version: ["3.9", "3.14"]

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
      - run: uv python install ${{ matrix.python-version }}
      - run: uv sync --frozen

      - run: make download-app
      - run: make test-cov

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.14'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
